
service: webhook-lambda-mqtt
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

  stage: dev
  region: us-east-1

functions:
  publish2Iot:
    handler: handler.publish2Iot
    events:
      - http:
          path: messages/publish
          method: post
          
plugins:
  - serverless-python-requirements
